//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ada_mvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleDeAsistencias
    {
        public int IdDetalle { get; set; }
        public Nullable<int> IdAsistencia { get; set; }
        public Nullable<System.DateTime> FechaHoraEntrada { get; set; }
        public Nullable<System.DateTime> FechaHoraSalida { get; set; }
        public string Observacion { get; set; }
    
        public virtual Asistencias Asistencias { get; set; }
    }
}
