//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ada_mvc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class bdEntities : DbContext
    {
        public bdEntities()
            : base("name=bdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<Asistencias> Asistencias { get; set; }
        public virtual DbSet<DetalleDeAsistencias> DetalleDeAsistencias { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<EquiposTecnologicos> EquiposTecnologicos { get; set; }
        public virtual DbSet<LogTablas> LogTablas { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    
        public virtual ObjectResult<SpAreas_Result> SpAreas(Nullable<int> idArea, string nombre, string funcion, string observacion, string w_Operacion, ObjectParameter o_Mensaje)
        {
            var idAreaParameter = idArea.HasValue ?
                new ObjectParameter("idArea", idArea) :
                new ObjectParameter("idArea", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var funcionParameter = funcion != null ?
                new ObjectParameter("Funcion", funcion) :
                new ObjectParameter("Funcion", typeof(string));
    
            var observacionParameter = observacion != null ?
                new ObjectParameter("Observacion", observacion) :
                new ObjectParameter("Observacion", typeof(string));
    
            var w_OperacionParameter = w_Operacion != null ?
                new ObjectParameter("W_Operacion", w_Operacion) :
                new ObjectParameter("W_Operacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpAreas_Result>("SpAreas", idAreaParameter, nombreParameter, funcionParameter, observacionParameter, w_OperacionParameter, o_Mensaje);
        }
    
        public virtual ObjectResult<SpAsistencias_Result> SpAsistencias(Nullable<int> idAsistencia, Nullable<int> codEmpleado, string w_Operacion, ObjectParameter o_Mensaje)
        {
            var idAsistenciaParameter = idAsistencia.HasValue ?
                new ObjectParameter("IdAsistencia", idAsistencia) :
                new ObjectParameter("IdAsistencia", typeof(int));
    
            var codEmpleadoParameter = codEmpleado.HasValue ?
                new ObjectParameter("CodEmpleado", codEmpleado) :
                new ObjectParameter("CodEmpleado", typeof(int));
    
            var w_OperacionParameter = w_Operacion != null ?
                new ObjectParameter("W_Operacion", w_Operacion) :
                new ObjectParameter("W_Operacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpAsistencias_Result>("SpAsistencias", idAsistenciaParameter, codEmpleadoParameter, w_OperacionParameter, o_Mensaje);
        }
    
        public virtual ObjectResult<SpDetalleDeAsistencias_Result> SpDetalleDeAsistencias(Nullable<int> idDetalle, Nullable<int> idAsistencia, Nullable<System.DateTime> fechaHoraEntrada, Nullable<System.DateTime> fechaHoraSalida, string obervacion, string w_Operacion, ObjectParameter o_Mensaje)
        {
            var idDetalleParameter = idDetalle.HasValue ?
                new ObjectParameter("IdDetalle", idDetalle) :
                new ObjectParameter("IdDetalle", typeof(int));
    
            var idAsistenciaParameter = idAsistencia.HasValue ?
                new ObjectParameter("IdAsistencia", idAsistencia) :
                new ObjectParameter("IdAsistencia", typeof(int));
    
            var fechaHoraEntradaParameter = fechaHoraEntrada.HasValue ?
                new ObjectParameter("FechaHoraEntrada", fechaHoraEntrada) :
                new ObjectParameter("FechaHoraEntrada", typeof(System.DateTime));
    
            var fechaHoraSalidaParameter = fechaHoraSalida.HasValue ?
                new ObjectParameter("FechaHoraSalida", fechaHoraSalida) :
                new ObjectParameter("FechaHoraSalida", typeof(System.DateTime));
    
            var obervacionParameter = obervacion != null ?
                new ObjectParameter("Obervacion", obervacion) :
                new ObjectParameter("Obervacion", typeof(string));
    
            var w_OperacionParameter = w_Operacion != null ?
                new ObjectParameter("W_Operacion", w_Operacion) :
                new ObjectParameter("W_Operacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpDetalleDeAsistencias_Result>("SpDetalleDeAsistencias", idDetalleParameter, idAsistenciaParameter, fechaHoraEntradaParameter, fechaHoraSalidaParameter, obervacionParameter, w_OperacionParameter, o_Mensaje);
        }
    
        public virtual ObjectResult<SpEmpleados_Result> SpEmpleados(Nullable<int> codEmpleado, string nombre, string apellido, string identificacion, string cargo, Nullable<int> idArea, string observacion, string w_Operacion, ObjectParameter o_Mensaje)
        {
            var codEmpleadoParameter = codEmpleado.HasValue ?
                new ObjectParameter("CodEmpleado", codEmpleado) :
                new ObjectParameter("CodEmpleado", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var identificacionParameter = identificacion != null ?
                new ObjectParameter("Identificacion", identificacion) :
                new ObjectParameter("Identificacion", typeof(string));
    
            var cargoParameter = cargo != null ?
                new ObjectParameter("Cargo", cargo) :
                new ObjectParameter("Cargo", typeof(string));
    
            var idAreaParameter = idArea.HasValue ?
                new ObjectParameter("IdArea", idArea) :
                new ObjectParameter("IdArea", typeof(int));
    
            var observacionParameter = observacion != null ?
                new ObjectParameter("Observacion", observacion) :
                new ObjectParameter("Observacion", typeof(string));
    
            var w_OperacionParameter = w_Operacion != null ?
                new ObjectParameter("W_Operacion", w_Operacion) :
                new ObjectParameter("W_Operacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpEmpleados_Result>("SpEmpleados", codEmpleadoParameter, nombreParameter, apellidoParameter, identificacionParameter, cargoParameter, idAreaParameter, observacionParameter, w_OperacionParameter, o_Mensaje);
        }
    
        public virtual ObjectResult<SpEquipoTecnologicos_Result> SpEquipoTecnologicos(Nullable<int> idEquipo, string descripcion, string modelo, string marca, string numeroDeSerie, string codigoInterno, string estado, Nullable<int> codEmpleado, Nullable<decimal> valorMonetario, Nullable<int> creadoPorUserName, string observacion, string w_Operacion, ObjectParameter o_Mensaje)
        {
            var idEquipoParameter = idEquipo.HasValue ?
                new ObjectParameter("IdEquipo", idEquipo) :
                new ObjectParameter("IdEquipo", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var modeloParameter = modelo != null ?
                new ObjectParameter("Modelo", modelo) :
                new ObjectParameter("Modelo", typeof(string));
    
            var marcaParameter = marca != null ?
                new ObjectParameter("Marca", marca) :
                new ObjectParameter("Marca", typeof(string));
    
            var numeroDeSerieParameter = numeroDeSerie != null ?
                new ObjectParameter("NumeroDeSerie", numeroDeSerie) :
                new ObjectParameter("NumeroDeSerie", typeof(string));
    
            var codigoInternoParameter = codigoInterno != null ?
                new ObjectParameter("CodigoInterno", codigoInterno) :
                new ObjectParameter("CodigoInterno", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var codEmpleadoParameter = codEmpleado.HasValue ?
                new ObjectParameter("CodEmpleado", codEmpleado) :
                new ObjectParameter("CodEmpleado", typeof(int));
    
            var valorMonetarioParameter = valorMonetario.HasValue ?
                new ObjectParameter("ValorMonetario", valorMonetario) :
                new ObjectParameter("ValorMonetario", typeof(decimal));
    
            var creadoPorUserNameParameter = creadoPorUserName.HasValue ?
                new ObjectParameter("CreadoPorUserName", creadoPorUserName) :
                new ObjectParameter("CreadoPorUserName", typeof(int));
    
            var observacionParameter = observacion != null ?
                new ObjectParameter("Observacion", observacion) :
                new ObjectParameter("Observacion", typeof(string));
    
            var w_OperacionParameter = w_Operacion != null ?
                new ObjectParameter("W_Operacion", w_Operacion) :
                new ObjectParameter("W_Operacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpEquipoTecnologicos_Result>("SpEquipoTecnologicos", idEquipoParameter, descripcionParameter, modeloParameter, marcaParameter, numeroDeSerieParameter, codigoInternoParameter, estadoParameter, codEmpleadoParameter, valorMonetarioParameter, creadoPorUserNameParameter, observacionParameter, w_OperacionParameter, o_Mensaje);
        }
    
        public virtual ObjectResult<SpUsuarios_Result> SpUsuarios(Nullable<int> idUsuario, string nombre, string apellido, string cargo, string rolDeAcceso, string userName, string password, string observacion, string w_Operacion, ObjectParameter o_Mensaje)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var cargoParameter = cargo != null ?
                new ObjectParameter("Cargo", cargo) :
                new ObjectParameter("Cargo", typeof(string));
    
            var rolDeAccesoParameter = rolDeAcceso != null ?
                new ObjectParameter("RolDeAcceso", rolDeAcceso) :
                new ObjectParameter("RolDeAcceso", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var observacionParameter = observacion != null ?
                new ObjectParameter("Observacion", observacion) :
                new ObjectParameter("Observacion", typeof(string));
    
            var w_OperacionParameter = w_Operacion != null ?
                new ObjectParameter("W_Operacion", w_Operacion) :
                new ObjectParameter("W_Operacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpUsuarios_Result>("SpUsuarios", idUsuarioParameter, nombreParameter, apellidoParameter, cargoParameter, rolDeAccesoParameter, userNameParameter, passwordParameter, observacionParameter, w_OperacionParameter, o_Mensaje);
        }
    }
}
